version: '3.8'

services:
  frontend:
    build:
      context: ./m347-ref-card-03-fe
    networks:
      - cool-cars-network
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./m347-ref-card-03-be
    networks:
      - cool-cars-network
    ports:
      - "8080:8080"
    restart: always

networks:
  cool-cars-network:
    driver: bridge
