version: '3.8'

services:
  backend:
    image: coolcarssvegiu.azurecr.io/cool-cars-backend:1.1
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_URL=http://localhost:3000
    networks:
      - cool-cars-network

  frontend:
    image: coolcarssvegiu.azurecr.io/cool-cars-frontend:1.1
    ports:
      - "80:80"
    networks:
      - cool-cars-network

networks:
  cool-cars-network:
    driver: bridge
